### ISSUE TITLE
PHP CS-Fixer

### ISSUE THREAD

**Issue by ultrono** [f9webltd/laravel-api-response-helpers#2]
Add GitHub action to run PHP CS-Fixer and automatically submit any issues via a pull request

**Comment by JacekAndrzejewski** [comment]
If fixer will use only safe rules then I see no reason to make that action automatically add commit with formatted code, either after creating PR or even after merging. Because if changes are safe, then there's no point in reviewing that really.
Other solution would be to use something like GrumPHP to force fixer run before being able to commit changes.

**Comment by JacekAndrzejewski** [comment]
We also could use [ecs](https://github.com/symplify/easy-coding-standard) instead of PHP CS-Fixer, it's easier to work with IMO.
For almost fully automatic configuration and explanation of rules we can use [CS-Fixer configurator](https://mlocati.github.io/php-cs-fixer-configurator).

**Comment by ultrono** [comment]
@JacekAndrzejewski Larger packages tend to use a variation of https://github.com/spatie/laravel-backup/blob/main/.github/workflows/php-cs-fixer.yml - I was thinking of that to be honest :+1: 

Will look at ecs, not come across that before.

**Comment by gogl92** [comment]
Maybe Laravel Pint with github actions 🤔 https://laravelmagazine.com/blog/run-laravel-pint-as-part-of-your-ci-pipeline-with-github-actions
